name: Builds

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Login
        run: echo "${{ secrets.ALMALINUX }}" | podman login git.almalinux.org -u charles2 --password-stdin
      - name: Build PupaOS normal container
        run: |
          git clone https://git.almalinux.org/pupaos/container.git
          pushd container
          git checkout latest
          popd
          podman build -t git.almalinux.org/pupaos/container:latest container
      - name: Build PupaOS ISO container
        run: |
          git clone https://git.almalinux.org/pupaos/iso
          pushd iso
          git checkout latest
          popd
          podman build -t git.almalinux.org/pupaos/iso:a9 iso/a9
      - name: Push them all
        run: |
          podman push git.almalinux.org/pupaos/container:latest
          podman push git.almalinux.org/pupaos/iso:a9
