name: Builds

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Login
        run: echo "${{ secrets.CODEBERG }}" | podman login codeberg.org -u charles --password-stdin
      - name: Build PupaOS normal container
        run: |
          git clone https://codeberg.org/pupaos/container.git
          pushd container
          git checkout latest
          popd
          podman build -t codeberg.org/pupaos/container:latest container
      - name: Build PupaOS ISO container
        run: |
          git clone https://codeberg.org/pupaos/iso
          pushd iso
          git checkout latest
          popd
          podman build -t codeberg.org/pupaos/iso:r9 iso/r9
      - name: Push them all
        run: |
          podman push codeberg.org/pupaos/container:latest
          podman push codeberg.org/pupaos/iso:r9
